### ISSUE TITLE
LG U+ 070 인터넷전화 CPG-4020 Basic 인증으로 다운그레이드 불가

### ISSUE THREAD

**Issue by U-siro** [koreapyj/sip-mitm#1]
아무리 Basic으로 요청해도 Digest로 응답합니다.
다만 nonce를 빈 값으로 설정하고 cnonce를 받아내지 않게 하는 방법은 사용 가능한 것으로 보입니다만, 그래도 얻는 건 md5로 해시화된 암호 뿐입니다.

**Comment by koreapyj** [comment]
통신사향 단말은 그럴 수도 있습니다. 저는 M-스톤사의 기업용 인터넷전화에서만 테스트해보았습니다. 이쪽도 통신사에서 제공하긴 하지만 범용 단말이라 인증수단을 건드리는게 다소 부담이 있을거라..

**Comment by U-siro** [comment]
그렇군요.. 결론부터 이야기하자면 DNS단으로 풀긴 했습니다. 좋은 코드 오픈소스해주셔서 감사합니당 😆
